
/* This file was generated by idltool 53.23. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif
#ifndef LIBRARIES_ZIP_H
#include <libraries/zip.h>
#endif

/* forward declaration */
struct ZipIFace;

extern uint32               VARARGS68K _main_Obtain(struct ZipIFace *);
extern uint32               VARARGS68K _main_Release(struct ZipIFace *);
extern zip_int32_t          VARARGS68K _main_zip_archive_set_tempdir(struct ZipIFace *, struct zip * za, CONST_STRPTR tempdir);
extern zip_int32_t          VARARGS68K _main_zip_close(struct ZipIFace *, struct zip * za);
extern zip_int32_t          VARARGS68K _main_zip_delete(struct ZipIFace *, struct zip * za, zip_uint64_t idx);
extern zip_int64_t          VARARGS68K _main_zip_dir_add(struct ZipIFace *, struct zip * za, CONST_STRPTR name, zip_flags_t flags);
extern void                 VARARGS68K _main_zip_discard(struct ZipIFace *, struct zip * za);
extern void                 VARARGS68K _main_zip_error_clear(struct ZipIFace *, struct zip * za);
extern void                 VARARGS68K _main_zip_error_get(struct ZipIFace *, struct zip * za, zip_int32_t * zep, zip_int32_t * sep);
extern zip_int32_t          VARARGS68K _main_zip_error_get_sys_type(struct ZipIFace *, zip_int32_t ze);
extern zip_int32_t          VARARGS68K _main_zip_error_to_str(struct ZipIFace *, STRPTR buf, zip_uint64_t len, zip_int32_t ze, zip_int32_t se);
extern zip_int32_t          VARARGS68K _main_zip_fclose(struct ZipIFace *, struct zip_file * zf);
extern struct zip *         VARARGS68K _main_zip_fdopen(struct ZipIFace *, zip_int32_t fd_orig, zip_int32_t _flags, zip_int32_t * zep);
extern zip_int64_t          VARARGS68K _main_zip_file_add(struct ZipIFace *, struct zip * za, CONST_STRPTR name, struct zip_source * source, zip_flags_t flags);
extern void                 VARARGS68K _main_zip_file_error_clear(struct ZipIFace *, struct zip_file * zf);
extern void                 VARARGS68K _main_zip_file_error_get(struct ZipIFace *, struct zip_file * zf, zip_int32_t * zep, zip_int32_t * sep);
extern zip_int32_t          VARARGS68K _main_zip_file_extra_field_delete(struct ZipIFace *, struct zip * za, zip_uint64_t idx, zip_uint16_t ef_idx, zip_flags_t flags);
extern zip_int32_t          VARARGS68K _main_zip_file_extra_field_delete_by_id(struct ZipIFace *, struct zip * za, zip_uint64_t idx, zip_uint16_t ef_id, zip_uint16_t ef_idx, zip_flags_t flags);
extern zip_int32_t          VARARGS68K _main_zip_file_extra_field_set(struct ZipIFace *, struct zip * za, zip_uint64_t idx, zip_uint16_t ef_id, zip_uint16_t ef_idx, const zip_uint8_t * data, zip_uint16_t len, zip_flags_t flags);
extern zip_int16_t          VARARGS68K _main_zip_file_extra_fields_count(struct ZipIFace *, struct zip * za, zip_uint64_t idx, zip_flags_t flags);
extern zip_int16_t          VARARGS68K _main_zip_file_extra_fields_count_by_id(struct ZipIFace *, struct zip * za, zip_uint64_t idx, zip_uint16_t ef_id, zip_flags_t flags);
extern const zip_uint8_t *  VARARGS68K _main_zip_file_extra_field_get(struct ZipIFace *, struct zip * za, zip_uint64_t idx, zip_uint16_t ef_idx, zip_uint16_t * idp, zip_uint16_t * lenp, zip_flags_t flags);
extern const zip_uint8_t *  VARARGS68K _main_zip_file_extra_field_get_by_id(struct ZipIFace *, struct zip * za, zip_uint64_t idx, zip_uint16_t ef_id, zip_uint16_t ef_idx, zip_uint16_t * lenp, zip_flags_t flags);
extern CONST_STRPTR         VARARGS68K _main_zip_file_get_comment(struct ZipIFace *, struct zip * za, zip_uint64_t idx, zip_uint32_t * lenp, zip_flags_t flags);
extern zip_int32_t          VARARGS68K _main_zip_file_get_external_attributes(struct ZipIFace *, struct zip * za, zip_uint64_t idx, zip_flags_t flags, zip_uint8_t * opsys, zip_uint32_t * attributes);
extern zip_int32_t          VARARGS68K _main_zip_file_rename(struct ZipIFace *, struct zip * za, zip_uint64_t idx, CONST_STRPTR name, zip_flags_t flags);
extern zip_int32_t          VARARGS68K _main_zip_file_replace(struct ZipIFace *, struct zip * za, zip_uint64_t idx, struct zip_source * source, zip_flags_t flags);
extern zip_int32_t          VARARGS68K _main_zip_file_set_comment(struct ZipIFace *, struct zip * za, zip_uint64_t idx, CONST_STRPTR comment, zip_uint16_t len, zip_flags_t flags);
extern zip_int32_t          VARARGS68K _main_zip_file_set_external_attributes(struct ZipIFace *, struct zip * za, zip_uint64_t idx, zip_flags_t flags, zip_uint8_t opsys, zip_uint32_t attributes);
extern CONST_STRPTR         VARARGS68K _main_zip_file_strerror(struct ZipIFace *, struct zip_file * zf);
extern struct zip_file *    VARARGS68K _main_zip_fopen(struct ZipIFace *, struct zip * za, CONST_STRPTR fname, zip_flags_t flags);
extern struct zip_file *    VARARGS68K _main_zip_fopen_encrypted(struct ZipIFace *, struct zip * za, CONST_STRPTR fname, zip_flags_t flags, CONST_STRPTR password);
extern struct zip_file *    VARARGS68K _main_zip_fopen_index(struct ZipIFace *, struct zip * za, zip_uint64_t index, zip_flags_t flags);
extern struct zip_file *    VARARGS68K _main_zip_fopen_index_encrypted(struct ZipIFace *, struct zip * za, zip_uint64_t index, zip_flags_t flags, CONST_STRPTR password);
extern zip_int64_t          VARARGS68K _main_zip_fread(struct ZipIFace *, struct zip_file * zf, APTR outbuf, zip_uint64_t toread);
extern CONST_STRPTR         VARARGS68K _main_zip_get_archive_comment(struct ZipIFace *, struct zip * za, zip_int32_t * lenp, zip_flags_t flags);
extern zip_int32_t          VARARGS68K _main_zip_get_archive_flag(struct ZipIFace *, struct zip * za, zip_uint32_t flag, zip_flags_t flags);
extern CONST_STRPTR         VARARGS68K _main_zip_get_name(struct ZipIFace *, struct zip * za, zip_uint64_t idx, zip_flags_t flags);
extern zip_int64_t          VARARGS68K _main_zip_get_num_entries(struct ZipIFace *, struct zip * za, zip_flags_t flags);
extern zip_int64_t          VARARGS68K _main_zip_name_locate(struct ZipIFace *, struct zip * za, CONST_STRPTR fname, zip_flags_t flags);
extern struct zip *         VARARGS68K _main_zip_open(struct ZipIFace *, CONST_STRPTR fn, zip_int32_t _flags, zip_int32_t * zep);
extern zip_int32_t          VARARGS68K _main_zip_set_archive_comment(struct ZipIFace *, struct zip * za, CONST_STRPTR comment, zip_uint16_t len);
extern zip_int32_t          VARARGS68K _main_zip_set_archive_flag(struct ZipIFace *, struct zip * za, zip_uint32_t flag, zip_int32_t value);
extern zip_int32_t          VARARGS68K _main_zip_set_default_password(struct ZipIFace *, struct zip * za, CONST_STRPTR passwd);
extern zip_int32_t          VARARGS68K _main_zip_set_file_compression(struct ZipIFace *, struct zip * za, zip_uint64_t idx, zip_int32_t method, zip_flags_t flags);
extern struct zip_source *  VARARGS68K _main_zip_source_buffer(struct ZipIFace *, struct zip * za, CONST_APTR data, zip_uint64_t len, zip_int32_t freep);
extern struct zip_source *  VARARGS68K _main_zip_source_file(struct ZipIFace *, struct zip * za, CONST_STRPTR fname, zip_uint64_t start, zip_int64_t len);
extern struct zip_source *  VARARGS68K _main_zip_source_filep(struct ZipIFace *, struct zip * za, FILE * file, zip_uint64_t start, zip_int64_t len);
extern void                 VARARGS68K _main_zip_source_free(struct ZipIFace *, struct zip_source * src);
extern struct zip_source *  VARARGS68K _main_zip_source_function(struct ZipIFace *, struct zip * za, zip_source_callback zcb, APTR ud);
extern struct zip_source *  VARARGS68K _main_zip_source_zip(struct ZipIFace *, struct zip * za, struct zip * srcza, zip_uint64_t srcidx, zip_flags_t flags, zip_uint64_t start, zip_int64_t len);
extern zip_int32_t          VARARGS68K _main_zip_stat(struct ZipIFace *, struct zip * za, CONST_STRPTR fname, zip_flags_t flags, struct zip_stat * st);
extern zip_int32_t          VARARGS68K _main_zip_stat_index(struct ZipIFace *, struct zip * za, zip_uint64_t index, zip_flags_t flags, struct zip_stat * st);
extern void                 VARARGS68K _main_zip_stat_init(struct ZipIFace *, struct zip_stat * st);
extern CONST_STRPTR         VARARGS68K _main_zip_strerror(struct ZipIFace *, struct zip * za);
extern zip_int32_t          VARARGS68K _main_zip_unchange(struct ZipIFace *, struct zip * za, zip_uint64_t idx);
extern zip_int32_t          VARARGS68K _main_zip_unchange_all(struct ZipIFace *, struct zip * za);
extern zip_int32_t          VARARGS68K _main_zip_unchange_archive(struct ZipIFace *, struct zip * za);
extern zip_error_t *        VARARGS68K _main_zip_get_error(struct ZipIFace *, struct zip * za);
extern int                  VARARGS68K _main_zip_error_code_zip(struct ZipIFace *, const struct zip_error * error);
extern int                  VARARGS68K _main_zip_error_code_system(struct ZipIFace *, const struct zip_error * error);
extern void                 VARARGS68K _main_zip_error_fini(struct ZipIFace *, struct zip_error * error);
extern void                 VARARGS68K _main_zip_error_init(struct ZipIFace *, struct zip_error * error);
extern void                 VARARGS68K _main_zip_error_init_with_code(struct ZipIFace *, struct zip_error * error, int ze);
extern void                 VARARGS68K _main_zip_error_set(struct ZipIFace *, struct zip_error * error, int ze, int se);
extern const char *         VARARGS68K _main_zip_error_strerror(struct ZipIFace *, struct zip_error * error);
extern int                  VARARGS68K _main_zip_error_system_type(struct ZipIFace *, const struct zip_error * error);
extern zip_int64_t          VARARGS68K _main_zip_error_to_data(struct ZipIFace *, const struct zip_error * error, void * data, zip_uint64_t length);
extern struct zip *         VARARGS68K _main_zip_open_from_source(struct ZipIFace *, struct zip_source * zs, int flags, struct zip_error * ze);
